import {chromium} from 'playwright';
import {PNG} from 'pngjs';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const base=process.argv[2]||'http://127.0.0.1:4173/DesignSpace/';
const directory='artifacts/verification/templates';await mkdir(directory,{recursive:true});
const browser=await chromium.launch({headless:true,args:['--use-angle=swiftshader','--enable-webgl','--enable-unsafe-swiftshader','--no-sandbox']});
const context=await browser.newContext({viewport:{width:1600,height:1000},deviceScaleFactor:1,acceptDownloads:true});
const page=await context.newPage(),errors=[],log=[],results=[];
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>log.push(m.type()+': '+m.text()));
const snapshot=()=>page.evaluate(()=>globalThis.designSpaceDiagnostics);
const settle=()=>page.waitForTimeout(400);
async function check(name,run){await run();results.push(name);console.log('PASS',name);}
async function control(name){await page.waitForFunction(n=>globalThis.designSpaceDiagnostics?.controls.some(c=>c.Name===n),name,{timeout:15000});return(await snapshot()).controls.find(c=>c.Name===name);}
async function click(name){let c=await control(name);await settle();c=await control(name);await page.mouse.click(c.X+c.Width/2,c.Y+c.Height/2);await settle();}
async function edit(name,value){await click(name);await page.waitForFunction(n=>globalThis.designSpaceDiagnostics.focus===n,name);await page.keyboard.press('Control+A');await page.keyboard.insertText(value);await page.waitForFunction(({name,value})=>globalThis.designSpaceDiagnostics.controls.find(c=>c.Name===name)?.Text===value,{name,value});await page.keyboard.press('Tab');await settle();}
const target=(s,name)=>s.nodes.find(n=>n.name===name);
const part=(s,name)=>s.interaction.parts.find(n=>n.name===name+'_Chrome');
async function point(x,y){const s=(await snapshot()).surface;return{x:s.x+s.panX+x*s.zoom,y:s.y+s.panY+y*s.zoom};}
async function move(x,y){const p=await point(x,y);await page.mouse.move(p.x,p.y);await settle();}
async function tap(x,y){const p=await point(x,y);await page.mouse.click(p.x,p.y);await settle();}
async function color(name,value){await page.waitForFunction(({name,value})=>globalThis.designSpaceDiagnostics.interaction.parts.find(n=>n.name===name+'_Chrome')?.background===value,{name,value});}
function template(type,key){return `<ControlTemplate x:Key="${key}" TargetType="${type}"><Border x:Name="Chrome" Background="{TemplateBinding Background}" BorderBrush="Transparent" BorderThickness="2"><ContentPresenter HorizontalAlignment="Center" VerticalAlignment="Center"/></Border><ControlTemplate.Triggers><Trigger Property="IsMouseOver" Value="True"><Setter TargetName="Chrome" Property="Background" Value="#FF7A3BD1"/></Trigger><MultiTrigger><MultiTrigger.Conditions><Condition Property="IsMouseOver" Value="True"/><Condition Property="IsPressed" Value="True"/></MultiTrigger.Conditions><Setter TargetName="Chrome" Property="Background" Value="#FFE06D1B"/></MultiTrigger><Trigger Property="IsChecked" Value="True"><Setter TargetName="Chrome" Property="Background" Value="#FF00805A"/></Trigger><Trigger Property="IsEnabled" Value="False"><Setter TargetName="Chrome" Property="Opacity" Value="0.4"/></Trigger></ControlTemplate.Triggers></ControlTemplate>`;}
const fixture=`<Canvas xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" Width="960" Height="560" Background="White"><Canvas.Resources>${template('Button','T')}${template('CheckBox','C')}</Canvas.Resources><TextBlock Canvas.Left="70" Canvas.Top="50" Width="800" Height="50" FontSize="28" Text="Interactive control templates"/><Button x:Name="A" Canvas.Left="100" Canvas.Top="140" Width="180" Height="70" Background="#FF0078D4" Foreground="White" Template="{StaticResource T}" Content="Press and hover"/><Button x:Name="B" Canvas.Left="420" Canvas.Top="140" Width="180" Height="70" Background="#FF0078D4" Foreground="White" Template="{StaticResource T}" Content="Independent instance"/><CheckBox x:Name="Check" Canvas.Left="100" Canvas.Top="320" Width="180" Height="70" Background="#FF0078D4" Foreground="White" Template="{StaticResource C}" Content="Transient check"/><Button x:Name="Disabled" Canvas.Left="420" Canvas.Top="320" Width="180" Height="70" Background="#FF0078D4" Template="{StaticResource T}" IsEnabled="FALSE" Content="Disabled"/></Canvas>`;
let initial,id,source;
try{
 await page.goto(base+'?diagnostics=1',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>globalThis.designSpaceDiagnostics?.ready&&globalThis.designSpaceDiagnostics.drawCount>0,null,{timeout:180000});
 await check('templated controls import with namescoped generated visuals',async()=>{const pending=page.waitForEvent('filechooser');await click('Open design');await(await pending).setFiles({name:'TemplateStudy.xaml',mimeType:'text/plain',buffer:Buffer.from(fixture)});await page.waitForFunction(()=>globalThis.designSpaceDiagnostics.nodes.some(n=>n.name==='A'));await click('Design view');await click('Fit artboard');initial=await snapshot();id=initial.workspace.active;assert.ok(part(initial,'A')&&part(initial,'B'));assert.notEqual(part(initial,'A').id,part(initial,'B').id);});
 await check('hover preview changes only the hovered template instance',async()=>{await click('Test control interactions');await move(160,175);await color('A','#FF7A3BD1');const s=await snapshot();assert.equal(part(s,'B').background,'#FF0078D4');assert.equal(s.revision,initial.revision);assert.equal(s.xaml,initial.xaml);await page.screenshot({path:directory+'/template-hover.png'});});
 await check('repeated pointer motion within a control reuses its preview tree',async()=>{const before=await snapshot();await move(170,170);await move(180,180);assert.equal((await snapshot()).interaction.builds,before.interaction.builds);});
 await check('captured press activates MultiTrigger without editing geometry',async()=>{await move(160,175);await page.mouse.down();await settle();await color('A','#FFE06D1B');const s=await snapshot();assert.equal(s.interaction.state.Pressed,target(s,'A').id);assert.equal(s.revision,initial.revision);await page.screenshot({path:directory+'/template-pressed.png'});});
 await check('dragging outside cancels press visuals and release does not mutate source',async()=>{await move(340,250);await color('A','#FF0078D4');await page.mouse.up();await settle();assert.equal((await snapshot()).interaction.state.Pressed,null);assert.equal((await snapshot()).xaml,initial.xaml);});
 await check('Tab navigation changes preview focus and skips disabled controls',async()=>{await tap(160,175);let s=await snapshot();assert.equal(s.interaction.state.Focused,target(s,'A').id);await page.keyboard.press('Tab');await settle();s=await snapshot();assert.equal(s.interaction.state.Focused,target(s,'B').id);await page.keyboard.press('Tab');await settle();s=await snapshot();assert.equal(s.interaction.state.Focused,target(s,'Check').id);await page.keyboard.press('Tab');await settle();s=await snapshot();assert.equal(s.interaction.state.Focused,target(s,'A').id);
   for(const name of ['Check','B','A']){
     await page.keyboard.press('Shift+Tab');await settle();s=await snapshot();
     assert.equal(s.interaction.state.Focused,target(s,name).id,'Shift+Tab moves exactly one preview target');
     assert.equal(s.focus,'Designer keyboard focus','Tab retains the real focus proxy');
   }
 });
 await check('checkbox input changes preview only and preserves base checked state',async()=>{await tap(160,355);await color('Check','#FF00805A');const s=await snapshot();assert.equal(s.interaction.state.Checked[target(s,'Check').id],true);assert.equal(target(s,'Check').properties.IsChecked,undefined);assert.equal(s.revision,initial.revision);});
 await check('keyboard activation toggles the focused checkbox on release',async()=>{await page.keyboard.down('Space');await settle();let s=await snapshot();assert.equal(s.interaction.state.Pressed,target(s,'Check').id);await page.keyboard.up('Space');await settle();s=await snapshot();assert.equal(s.interaction.state.Checked[target(s,'Check').id],false);assert.equal(s.interaction.state.Pressed,null);});
 await check('disabled controls neither capture nor activate',async()=>{await tap(500,355);let s=await snapshot();assert.equal(s.interaction.state.Focused,null);assert.equal(s.interaction.state.Pressed,null);assert.equal(part(s,'Disabled').opacity,'0.4');});
 await check('preview keyboard commands cannot nudge or delete base objects',async()=>{await page.keyboard.press('Delete');await page.keyboard.press('ArrowRight');await page.keyboard.press('Control+D');await settle();const s=await snapshot();assert.equal(s.revision,initial.revision);assert.equal(s.nodes.length,initial.nodes.length);assert.equal(s.xaml,initial.xaml);});
 await check('Escape clears all input and returns to design',async()=>{await page.keyboard.press('Escape');await settle();const s=await snapshot();assert.equal(s.interaction.enabled,false);assert.equal(s.interaction.state.Hovered,null);assert.equal(s.interaction.state.Focused,null);assert.deepEqual(s.interaction.state.Checked,{});assert.equal(part(s,'Check').background,'#FF0078D4');});
 await check('rendered trigger colors match the actual artboard pixels',async()=>{await click('Test control interactions');await move(160,175);await color('A','#FF7A3BD1');const p=await point(115,155),png=PNG.sync.read(await page.screenshot()),i=(Math.round(p.y)*png.width+Math.round(p.x))*4;assert.deepEqual([...png.data.subarray(i,i+3)],[122,59,209]);await page.keyboard.press('Escape');await settle();});
 await check('template source saves one revision and undo preserves a stale draft',async()=>{await click('Open Templates panel');await control('ControlTemplate source');source=(await snapshot()).controls.find(c=>c.Name==='ControlTemplate source').Text;assert.ok(source.includes('ControlTemplate'));await edit('ControlTemplate source',source.replaceAll('#FF7A3BD1','#FF8044AA'));const before=await snapshot();await click('Save control template');await page.waitForFunction(r=>globalThis.designSpaceDiagnostics.revision===r+1,before.revision);await settle();await edit('ControlTemplate source',source.replaceAll('#FF7A3BD1','#FF9944BB'));await click('Undo');await settle();const undone=await snapshot();await click('Save control template');const after=await snapshot();assert.equal(after.revision,undone.revision);assert.ok(after.status.includes('stale'));await click('Reload control template');});
 await check('interactive template sample is editable and applies to the selection',async()=>{await tap(160,175);await click('New interactive control template');const text=(await snapshot()).controls.find(c=>c.Name==='ControlTemplate source').Text;assert.ok(text.includes('IsPressed')&&text.includes('IsKeyboardFocused'));await click('Save control template');await click('Apply control template');const s=await snapshot();assert.ok(target(s,'A').properties.Template.includes('InteractiveButtonTemplate'));await page.screenshot({path:directory+'/template-source-authoring.png'});});
 await check('workspace export preserves trigger source rather than transient input',async()=>{await click('Test control interactions');await tap(160,355);const pending=page.waitForEvent('download');await click('Save workspace');const file=await pending;await file.saveAs(directory+'/template-workspace.designspace-workspace');const raw=await readFile(directory+'/template-workspace.designspace-workspace','utf8');assert.ok(raw.includes('ControlTemplate.Triggers'));assert.ok(!raw.includes('Hovered')&&!raw.includes('CheckedOverrides'));const s=await snapshot();assert.equal(target(s,'Check').properties.IsChecked,undefined);});
 assert.deepEqual(errors,[]);const final=await snapshot();assert.deepEqual(final.interaction.warnings,[]);assert.deepEqual(final.rendering.warnings,[]);assert.deepEqual(final.rendering.previewWarnings,[]);
}catch(error){await writeFile(directory+'/failure.txt',String(error.stack??error));await page.screenshot({path:directory+'/failure.png'}).catch(()=>{});throw error;}
finally{await writeFile(directory+'/results.json',JSON.stringify({passed:results.length,tests:results,errors},null,2));await writeFile(directory+'/diagnostics.json',JSON.stringify(await snapshot().catch(()=>null)??null,null,2));await writeFile(directory+'/browser.log',log.join('\n'));await browser.close();}
