using System.Collections.Immutable;
using DesignSpace.Core;
using DesignSpace.Engine;
using DesignSpace.Rendering.Skia;
using DesignSpace.Xaml;
using SkiaSharp;

internal static class VectorRenderingTests
{
    public static (int Passed,int Failed) Run()
    {
        var passed=0;var failed=0;
        void Test(string name,Action test){try{test();passed++;Console.WriteLine("PASS vector: "+name);}catch(Exception e){failed++;Console.Error.WriteLine("FAIL vector: "+name+": "+e);}}
        void Check(bool condition,string message="Assertion failed"){if(!condition)throw new Exception(message);}
        void Near(double a,double b,double eps=.001){if(Math.Abs(a-b)>eps)throw new Exception($"Expected {a}, got {b}");}
        void Reject(Action action){try{action();}catch(Exception){return;}throw new Exception("Expected rejection");}
        DesignNode Shape(string name,double x,double y,double w,double h,string type="Rectangle")=>DesignNode.Create(type,name,x,y,w,h).Set("Fill","Red").Set("StrokeThickness","0");
        DesignDocument Doc(params DesignNode[] nodes)=>new(){Root=DesignNode.Create("Canvas","Root",0,0,300,240).Set("Background","White") with { Children=nodes.ToImmutableArray() }};
        bool IsRed(SKBitmap bitmap,int x,int y)=>bitmap.GetPixel(x,y).Red>220&&bitmap.GetPixel(x,y).Green<30;
        SKBitmap Render(DesignDocument doc){using var renderer=new DesignRenderer();return SKBitmap.Decode(renderer.ExportPng(new LayoutEngine(renderer).Arrange(DesignPreview.Resolve(doc.Root)),1));}
        VectorPath WorldPath(DesignNode n)=>VectorMath.Transform(VectorGeometry.Local(n,new(n.Number("Width"),n.Number("Height"))),DMatrix.Translate(n.Number("Canvas.Left"),n.Number("Canvas.Top")));
        Test("path geometry hit ignores empty bounding-box corners",()=>{var n=Shape("P",10,10,100,100,"Path").Set("Data","M50 0L100 100L0 100Z");var l=new LayoutEngine().Arrange(Doc(n).Root);Check(l.HitTest(new(11,11)) is null);Check(l.HitTest(new(60,60))?.Node.Id==n.Id);});
        Test("stroke-only paths do not capture their interior",()=>{var n=Shape("P",10,10,100,100,"Path").Set("Data","M0 0H100V100H0Z").Set("Stroke","Black") with { Properties=Shape("P",10,10,100,100,"Path").Properties.Remove("Fill") };n=n.Set("Data","M0 0H100V100H0Z").Set("Stroke","Black");var l=new LayoutEngine().Arrange(Doc(n).Root);Check(l.HitTest(new(60,60)) is null);Check(l.HitTest(new(10,60)) is not null);});
        Test("evenodd holes match raster and picking",()=>{var n=Shape("P",10,10,100,100,"Path").Set("Data","F0M0 0H100V100H0ZM20 20H80V80H20Z");var d=Doc(n);var l=new LayoutEngine().Arrange(d.Root);using var bitmap=Render(d);Check(!IsRed(bitmap,60,60));Check(l.HitTest(new(60,60)) is null);Check(IsRed(bitmap,20,20));});
        Test("nonzero winding fills nested contours",()=>{var n=Shape("P",10,10,100,100,"Path").Set("Data","F1M0 0H100V100H0ZM20 20H80V80H20Z");using var b=Render(Doc(n));Check(IsRed(b,60,60));});
        Test("quadratic path renders without SVG conversion",()=>{var n=Shape("P",20,20,100,100,"Path").Set("Data","M0 100Q50-100 100 100Z");using var b=Render(Doc(n));Check(IsRed(b,70,80));});
        Test("arc path renders exact ellipse",()=>{var n=Shape("P",20,20,100,60,"Path");n=VectorGeometry.WithPath(n,VectorGeometry.Local(Shape("E",0,0,100,60,"Ellipse"),new(100,60)));using var b=Render(Doc(n));Check(IsRed(b,70,50));Check(!IsRed(b,21,21));});
        Test("path stretch does not multiply stroke width",()=>{var n=Shape("P",10,10,200,100,"Path").Set("Data","M0 0H10V10H0Z").Set("Stretch","Fill").Set("Stroke","Black").Set("StrokeThickness","2").Set("Fill","Transparent");using var b=Render(Doc(n));Check(b.GetPixel(10,50).Red<100);Check(b.GetPixel(15,50).Red>200);});
        Test("uniform stretch centers the shape",()=>{var n=Shape("P",10,10,200,200,"Path").Set("Data","M0 0H100V50H0Z").Set("Stretch","Uniform");using var b=Render(Doc(n));Check(IsRed(b,50,80));Check(!IsRed(b,50,30));});
        Test("Auto-sized path gets intrinsic geometry bounds",()=>{var n=new DesignNode{Type="Path"}.Set(DesignNode.NameKey,"P").Set("Data","M0 0H100V50H0Z").Set("Fill","Red").Set("StrokeThickness","0");var l=new LayoutEngine().Arrange(Doc(n).Root);Near(100,l.ById[n.Id].Bounds.Width);Near(50,l.ById[n.Id].Bounds.Height);});
        Test("explicit negative-direction line endpoints are honored",()=>{var n=Shape("L",20,20,100,100,"Line").Set("X1","100").Set("Y1","0").Set("X2","0").Set("Y2","100").Set("Stroke","Black").Set("StrokeThickness","2");var l=new LayoutEngine().Arrange(Doc(n).Root);Check(l.HitTest(new(40,100)) is not null);Check(l.HitTest(new(40,40)) is null);});
        foreach(var type in new[]{"Rectangle","Ellipse","Line"})Test("convert "+type+" retains identity and undo",()=>{var n=Shape("Shape",20,30,100,80,type);var s=new DesignSession(Doc(n));s.Select(n.Id);PathCommands.Convert(s,new LayoutEngine().Arrange(s.Document.Root));Check(s.Index.Find(n.Id)?.Type=="Path");Near(20,s.Index.Find(n.Id)!.Number("Canvas.Left"));s.Undo();Check(ReferenceEquals(n,s.Index.Find(n.Id)));});
        Test("rectangle conversion keeps raster footprint",()=>{var n=Shape("R",20,20,80,60);var s=new DesignSession(Doc(n));using var before=Render(s.Document);s.Select(n.Id);PathCommands.Convert(s,new LayoutEngine().Arrange(s.Document.Root));using var after=Render(s.Document);for(var y=5;y<110;y+=3)for(var x=5;x<120;x+=3)Check(before.GetPixel(x,y)==after.GetPixel(x,y));});
        Test("path resize scaling changes vector geometry",()=>{var n=PathCommands.CreateNode("P",VectorPathCodec.Parse("M0 0H100V50H0Z"));var p=VectorGeometry.Local(n,new(n.Number("Width"),n.Number("Height")));var scaled=VectorMath.Transform(p,DMatrix.Scale(2,2));Near(VectorMath.Bounds(p).Width*2,VectorMath.Bounds(scaled).Width);});
        foreach(var op in new[]{"Unite","Intersect","Subtract","Exclude"})Test(op+" truth table and undo",()=>
        {
            var a=Shape("A",20,20,80,80);var b=Shape("B",60,20,80,80);var s=new DesignSession(Doc(a,b));s.Select([a.Id,b.Id]);PathCommands.Combine(s,new LayoutEngine().Arrange(s.Document.Root),op);
            Check(s.Document.Root.Children.Length==1);var result=s.Document.Root.Children[0];Check(result.Id==a.Id);var p=WorldPath(result);
            for(var x=25;x<145;x+=10){var aa=x<100;var bb=x>60&&x<140;var expected=op switch{"Unite"=>aa||bb,"Intersect"=>aa&&bb,"Subtract"=>aa&&!bb,_=>aa!=bb};Check(VectorMath.Contains(p,new(x,50))==expected,op+" at "+x);}
            s.Undo();Check(ReferenceEquals(a,s.Document.Root.Children[0]));Check(ReferenceEquals(b,s.Document.Root.Children[1]));s.Redo();Check(s.Document.Root.Children.Length==1);
        });
        Test("empty intersection is an undoable deletion",()=>{var a=Shape("A",0,0,10,10);var b=Shape("B",100,100,10,10);var s=new DesignSession(Doc(a,b));s.Select([a.Id,b.Id]);PathCommands.Combine(s,new LayoutEngine().Arrange(s.Document.Root),"Intersect");Check(s.Document.Root.Children.IsEmpty);s.Undo();Check(s.Document.Root.Children.Length==2);});
        Test("divide yields three editable regions",()=>{var a=Shape("A",20,20,80,80);var b=Shape("B",60,20,80,80);var s=new DesignSession(Doc(a,b));s.Select([a.Id,b.Id]);PathCommands.Combine(s,new LayoutEngine().Arrange(s.Document.Root),"Divide");Check(s.Document.Root.Children.Length==3);for(var x=25;x<140;x+=10)Check(s.Document.Root.Children.Count(n=>VectorMath.Contains(WorldPath(n),new(x,50)))==1);});
        Test("compound creates an evenodd overlap hole",()=>{var a=Shape("A",20,20,80,80);var b=Shape("B",60,20,80,80);var s=new DesignSession(Doc(a,b));s.Select([a.Id,b.Id]);PathCommands.Combine(s,new LayoutEngine().Arrange(s.Document.Root),"Compound");Check(!VectorMath.Contains(WorldPath(s.Document.Root.Children[0]),new(80,50)));PathCommands.BreakApart(s,new LayoutEngine().Arrange(s.Document.Root));Check(s.Document.Root.Children.Length==2);});
        Test("booleans account for inherited transforms and padding",()=>{var a=Shape("A",20,20,80,80) with { Rotation=30 };var b=Shape("B",60,20,80,80);var host=DesignNode.Create("Canvas","Group",30,30,220,180).Set("Padding","5") with { Rotation=10,Children=[a,b] };var s=new DesignSession(Doc(host));s.Select([a.Id,b.Id]);PathCommands.Combine(s,new LayoutEngine().Arrange(s.Document.Root),"Unite");var l=new LayoutEngine().Arrange(s.Document.Root);var n=s.Index.Find(host.Id)!.Children[0];Check(l.HitTest(l.ById[n.Id].WorldTransform.Map(l.ById[n.Id].Bounds.Center)) is not null);});
        Test("animated operands are protected atomically",()=>{var a=Shape("A",20,20,80,80);var b=Shape("B",60,20,80,80);var d=Doc(a,b) with { Storyboards=[new(Guid.NewGuid(),"Anim",1,[new(a.Id,"Opacity",[new(0,0),new(1,1)])])] };var s=new DesignSession(d);s.Select([a.Id,b.Id]);Reject(()=>PathCommands.Combine(s,new LayoutEngine().Arrange(d.Root),"Unite"));Check(ReferenceEquals(d,s.Document));});
        Test("locked ancestors protect conversion",()=>{var n=Shape("R",20,20,80,60);var d=Doc(n);d=d with { Root=d.Root with { IsLocked=true } };var s=new DesignSession(d);s.Select(n.Id);Reject(()=>PathCommands.Convert(s,new LayoutEngine().Arrange(d.Root)));Check(s.Revision==0);});
        Test("per-shape opacity is not silently lost by combine",()=>{var a=Shape("A",20,20,80,80).Set("Opacity","0.5");var b=Shape("B",60,20,80,80);var s=new DesignSession(Doc(a,b));s.Select([a.Id,b.Id]);Reject(()=>PathCommands.Combine(s,new LayoutEngine().Arrange(s.Document.Root),"Unite"));});
        Test("invalid path edits leave session unchanged",()=>{var n=Shape("P",0,0,100,100,"Path").Set("Data","M0 0L100 100");var s=new DesignSession(Doc(n));s.Select(n.Id);Reject(()=>s.SetProperty("Data","M0 0C"));Check(s.Revision==0);});
        Test("clipping agrees between rendered pixels and picking",()=>{var target=Shape("Target",20,20,100,100);var mask=Shape("Mask",40,40,60,60,"Ellipse");var s=new DesignSession(Doc(target,mask));s.Select([target.Id,mask.Id]);PathCommands.ApplyClip(s,new LayoutEngine().Arrange(s.Document.Root));Check(s.Document.Root.Children.Length==1);using var b=Render(s.Document);Check(IsRed(b,70,70));Check(!IsRed(b,42,42));var l=new LayoutEngine().Arrange(s.Document.Root);Check(l.HitTest(new(42,42)) is null);Check(l.HitTest(new(70,70))?.Node.Id==target.Id);s.Undo();Check(s.Document.Root.Children.Length==2);});
        Test("clip release is undoable",()=>{var n=Shape("Target",20,20,100,100).Set("Clip","M0 0H50V100H0Z");var s=new DesignSession(Doc(n));s.Select(n.Id);PathCommands.ReleaseClip(s);Check(s.Index.Find(n.Id)!.Get("Clip")=="");s.Undo();Check(s.Index.Find(n.Id)!.Get("Clip").Length>0);});
        Test("ancestor geometry clip applies to children",()=>{var child=Shape("Child",0,0,100,100);var host=DesignNode.Create("Canvas","Host",20,20,100,100).Set("Clip","M0 0H50V100H0Z") with { Children=[child] };var d=Doc(host);using var b=Render(d);Check(IsRed(b,40,40));Check(!IsRed(b,90,40));Check(new LayoutEngine().Arrange(d.Root).HitTest(new(90,40)) is null);});
        Test("RectangleGeometry clip object is rendered",()=>{var n=Shape("R",20,20,100,100) with { PropertyElements=[$"<Rectangle.Clip xmlns='{DesignNode.PresentationNamespace}'><RectangleGeometry Rect='0,0,50,100'/></Rectangle.Clip>"] };using var b=Render(Doc(n));Check(IsRed(b,40,40));Check(!IsRed(b,90,40));});
        Test("PathGeometry object-form output matches data-string output",()=>{var d=XamlCodec.Parse($"<Canvas xmlns='{DesignNode.PresentationNamespace}' Width='300' Height='240' Background='White'><Path Width='100' Height='100' Fill='Red'><Path.Data><PathGeometry Figures='M10 10H90V90H10Z'/></Path.Data></Path></Canvas>").Document;using var b=Render(d);Check(IsRed(b,50,50));});
        Test("native and XAML preserve editable curves and clips",()=>{var n=Shape("P",20,20,100,100,"Path").Set("Data","F1 M0 0C0 100 100 100 100 0Z").Set("Clip","M0 0H80V100H0Z");var d=Doc(n);var native=NativeDocumentCodec.Read(NativeDocumentCodec.Write(d));Check(native.Root.Children[0].Get("Data")==n.Get("Data"));var xaml=XamlCodec.Parse(XamlCodec.Write(native)).Document;Check(xaml.Root.Children[0].Get("Clip")==n.Get("Clip"));});
        Test("warm geometry avoids repeated native path builds",()=>{var n=Shape("P",20,20,100,100,"Path").Set("Data","M0 0H100V100H0Z");using var r=new DesignRenderer();var l=new LayoutEngine(r).Arrange(Doc(n).Root);r.ExportPng(l,1);var builds=r.PathBuildCount;for(var i=0;i<3;i++)r.ExportPng(l,1);Check(r.PathBuildCount==builds);Check(r.PathCacheHits>=3);});
        Test("unite deterministically survives XAML roundtrip",()=>{var a=Shape("A",20,20,80,80);var b=Shape("B",60,20,80,80);var s=new DesignSession(Doc(a,b));s.Select([a.Id,b.Id]);PathCommands.Combine(s,new LayoutEngine().Arrange(s.Document.Root),"Unite");var output=XamlCodec.Write(s.Document);Check(XamlCodec.Write(XamlCodec.Parse(output).Document)==output);});
        Console.WriteLine($"Vector rendering: {passed} passed; {failed} failed.");return(passed,failed);
    }
}
