using System.Collections.Immutable;
using System.Diagnostics;
using System.Text.Json;
using DesignSpace.Core;
using DesignSpace.Engine;
using DesignSpace.Animation;
using DesignSpace.Xaml;
using DesignSpace.Rendering.Skia;
using SkiaSharp;

var passed=0;var failed=0;
void Test(string name,Action action) { try { action();passed++;Console.WriteLine("PASS "+name); } catch(Exception ex) { failed++;Console.Error.WriteLine("FAIL "+name+": "+ex); } }
void Check(bool condition,string message="Assertion failed") { if(!condition) throw new Exception(message); }
void Equal<T>(T expected,T actual) { if(!EqualityComparer<T>.Default.Equals(expected,actual)) throw new Exception($"Expected {expected}, got {actual}"); }
void Near(double expected,double actual,double tolerance=.001) { if(Math.Abs(expected-actual)>tolerance) throw new Exception($"Expected {expected}, got {actual}"); }
void Reject(Action action) { try { action(); } catch(Exception) { return; } throw new Exception("Expected rejection"); }
DesignNode Node(string type,string name,double x=0,double y=0,double w=50,double h=30)=>DesignNode.Create(type,name,x,y,w,h);
DesignNode Root(params DesignNode[] children)=>Node("Canvas","Root",0,0,400,300) with { Children=children.ToImmutableArray() };
string Wrap(string content)=>$"<Canvas xmlns='{DesignNode.PresentationNamespace}' xmlns:x='{DesignNode.XamlNamespace}' x:Name='Root' Width='400' Height='300'>{content}</Canvas>";
DesignNode Parse(string content)=>XamlCodec.Parse(Wrap(content)).Document.Root;

Test("index is reused for immutable roots",()=>{var r=Root(Node("Button","Button"));Check(ReferenceEquals(DesignIndex.For(r),DesignIndex.For(r)));});
Test("single edit preserves unaffected subtree references",()=>{var a=Node("Canvas","A") with { Children=[Node("Rectangle","C")] };var b=Node("Canvas","B") with { Children=[Node("Rectangle","D")] };var r=Root(a,b);var next=r.Update(a.Children[0].Id,n=>n.Set("Opacity","0.4"));Check(ReferenceEquals(b,next.Children[1]));Check(!ReferenceEquals(a,next.Children[0]));});
Test("identical property edit creates no revision or history",()=>{var s=new DesignSession(new(){Root=Root(Node("Rectangle","A"))});s.Select(s.Document.Root.Children[0].Id);s.SetProperty("Width","50");Equal(0L,s.Revision);Check(!s.CanUndo);});
Test("empty selection movement creates no history",()=>{var s=new DesignSession();s.Move(1,0);Equal(0L,s.Revision);});
Test("same selection does not emit duplicate events",()=>{var s=new DesignSession();var count=0;s.SelectionChanged+=(_,_)=>count++;s.Select(s.Document.Root.Id);s.Select(s.Document.Root.Id);Equal(1,count);});
Test("locked ancestor prevents property and movement edits",()=>{var child=Node("Rectangle","Child");var p=Node("Canvas","Parent") with { IsLocked=true,Children=[child] };var s=new DesignSession(new(){Root=Root(p)});s.Select(child.Id);s.SetProperty("Width","99");s.Move(4,0);Equal(0L,s.Revision);Equal("50",s.Index.Find(child.Id)!.Get("Width"));});
Test("locked ancestor prevents delete and duplicate",()=>{var child=Node("Rectangle","Child");var p=Node("Canvas","Parent") with { IsLocked=true,Children=[child] };var s=new DesignSession(new(){Root=Root(p)});s.Select(child.Id);s.Delete();s.Duplicate();Equal(0L,s.Revision);});
Test("locked container refuses insertion",()=>{var s=new DesignSession(new(){Root=Root() with { IsLocked=true }});Reject(()=>s.Add("Rectangle",new(0,0,20,20)));});
Test("reparent rejects cycles atomically",()=>{var child=Node("Canvas","Child");var parent=Node("Canvas","Parent") with { Children=[child] };var s=new DesignSession(new(){Root=Root(parent)});Reject(()=>s.Reparent(parent.Id,child.Id));Equal(0L,s.Revision);});
Test("reparent between Canvases preserves screen position",()=>{var child=Node("Rectangle","Child",10,15);var a=Node("Canvas","A",20,30,100,100) with { Children=[child] };var b=Node("Canvas","B",150,60,100,100);var s=new DesignSession(new(){Root=Root(a,b)});s.Reparent(child.Id,b.Id);var l=new LayoutEngine().Arrange(s.Document.Root);Near(30,l.ById[child.Id].Bounds.X);Near(45,l.ById[child.Id].Bounds.Y);s.Undo();Equal(a.Id,s.Index.ParentOf(child.Id)!.Id);});
Test("distribute uses equal edge gaps",()=>{var a=Node("Rectangle","A",0,0,20,20);var b=Node("Rectangle","B",35,0,20,20);var c=Node("Rectangle","C",100,0,20,20);var s=new DesignSession(new(){Root=Root(a,b,c)});s.Select([a.Id,b.Id,c.Id]);s.Distribute(true);Near(50,s.Index.Find(b.Id)!.Number("Canvas.Left"));});
Test("group retains order around other siblings",()=>{var a=Node("Rectangle","A");var b=Node("Rectangle","B");var c=Node("Rectangle","C");var s=new DesignSession(new(){Root=Root(a,b,c)});s.Select([a.Id,b.Id]);s.Group();Equal(c.Id,s.Document.Root.Children[1].Id);s.Ungroup();Equal(a.Id,s.Document.Root.Children[0].Id);Equal(b.Id,s.Document.Root.Children[1].Id);});
Test("noncontiguous grouping cannot silently alter z order",()=>{var a=Node("Rectangle","A");var b=Node("Rectangle","B");var c=Node("Rectangle","C");var s=new DesignSession(new(){Root=Root(a,b,c)});s.Select([a.Id,c.Id]);Reject(s.Group);Equal(0L,s.Revision);});
Test("matrix inverse round trip",()=>{var m=DMatrix.Translate(40,20)*DMatrix.Rotate(31)*DMatrix.Scale(2,.5);Check(m.TryInvert(out var inv));var p=inv.Map(m.Map(new(12,-3)));Near(12,p.X);Near(-3,p.Y);});
Test("singular matrix does not invert",()=>Check(!DMatrix.Scale(0,1).TryInvert(out _)));
Test("rotated ancestor participates in hit testing",()=>{var child=Node("Rectangle","Child",10,10,20,20);var p=Node("Canvas","Parent",100,100,100,100) with { Rotation=90,Children=[child] };var l=new LayoutEngine().Arrange(Root(p));var e=l.ById[child.Id];Equal(child.Id,l.HitTest(e.WorldTransform.Map(e.Bounds.Center))!.Node.Id);});
Test("ellipse corners do not hit filled ellipse",()=>{var n=Node("Ellipse","Circle",50,50,80,80);var l=new LayoutEngine().Arrange(Root(n));Check(l.HitTest(new(51,51)) is null);Equal(n.Id,l.HitTest(new(90,90))!.Node.Id);});
Test("clip bounds reject overflowing child",()=>{var child=Node("Rectangle","Child",60,0,20,20);var p=Node("Canvas","Parent",0,0,40,40).Set("ClipToBounds","True") with { Children=[child] };Check(new LayoutEngine().Arrange(Root(p)).HitTest(new(65,10)) is null);});
Test("hidden reserves layout but cannot hit",()=>{var a=Node("Rectangle","A").Set("Visibility","Hidden");var p=Node("StackPanel","P",0,0,100,100) with { Children=[a,Node("Rectangle","B")] };var l=new LayoutEngine().Arrange(Root(p));Near(30,l.Entries.Single(e=>e.Node.Name=="B").Bounds.Y);Check(!l.ById[a.Id].IsEffectivelyVisible);});
Test("ZIndex controls painting and picking",()=>{var a=Node("Rectangle","A").Set("Canvas.ZIndex","5");var b=Node("Rectangle","B");Equal(a.Id,new LayoutEngine().Arrange(Root(a,b)).HitTest(new(10,10))!.Node.Id);});
Test("Canvas right and bottom anchors",()=>{var n=Node("Rectangle","A",0,0,50,30);n=n with { Properties=n.Properties.Remove("Canvas.Left").Remove("Canvas.Top") };n=n.Set("Canvas.Right",10).Set("Canvas.Bottom",20);var b=new LayoutEngine().Arrange(Root(n)).ById[n.Id].Bounds;Near(340,b.X);Near(250,b.Y);});
Test("Grid Auto measures intrinsic content instead of fixed estimate",()=>{var root=Parse("<Grid x:Name='G' Width='300' Height='100'><Grid.ColumnDefinitions><ColumnDefinition Width='Auto'/><ColumnDefinition Width='*'/></Grid.ColumnDefinitions><Rectangle x:Name='A' Width='80' Height='20'/><Rectangle x:Name='B' Grid.Column='1' Height='20'/></Grid>");var l=new LayoutEngine().Arrange(root);var b=l.Entries.Single(e=>e.Node.Name=="B").Bounds;Near(80,b.X);Near(220,b.Width);});
Test("Grid weighted stars and gaps",()=>{var root=Parse("<Grid Width='310' Height='100' ColumnSpacing='10' ColumnDefinitions='*,2*'><Rectangle x:Name='A'/><Rectangle x:Name='B' Grid.Column='1'/></Grid>");var l=new LayoutEngine().Arrange(root);Near(100,l.Entries.Single(e=>e.Node.Name=="A").Bounds.Width);Near(110,l.Entries.Single(e=>e.Node.Name=="B").Bounds.X);Near(200,l.Entries.Single(e=>e.Node.Name=="B").Bounds.Width);});
Test("Grid star maximum redistributes remainder",()=>{var root=Parse("<Grid Width='300' Height='100'><Grid.ColumnDefinitions><ColumnDefinition Width='*' MaxWidth='80'/><ColumnDefinition Width='*'/></Grid.ColumnDefinitions><Rectangle x:Name='A'/><Rectangle x:Name='B' Grid.Column='1'/></Grid>");var l=new LayoutEngine().Arrange(root);Near(80,l.Entries.Single(e=>e.Node.Name=="A").Bounds.Width);Near(220,l.Entries.Single(e=>e.Node.Name=="B").Bounds.Width);});
Test("StackPanel spacing and margins are measured",()=>{var root=Parse("<StackPanel x:Name='P' Width='200' Spacing='5'><Rectangle x:Name='A' Width='20' Height='30' Margin='0,2,0,3'/><Rectangle x:Name='B' Width='20' Height='40'/></StackPanel>");var l=new LayoutEngine().Arrange(root);Near(80,l.Entries.Single(e=>e.Node.Name=="P").Bounds.Height);Near(40,l.Entries.Single(e=>e.Node.Name=="B").Bounds.Y);});
Test("measure cache survives repeated arrangements",()=>{var r=Root(Node("TextBlock","A").Set("Text","Measure once"));var engine=new LayoutEngine();engine.Arrange(r);var count=engine.MeasureEvaluations;engine.Arrange(r);Equal(count,engine.MeasureEvaluations);Check(engine.MeasureCacheHits>0);});
Test("transform group respects declaration order",()=>{var r=Parse("<Rectangle x:Name='A' Width='20' Height='20'><Rectangle.RenderTransform><TransformGroup><ScaleTransform ScaleX='2'/><TranslateTransform X='40'/></TransformGroup></Rectangle.RenderTransform></Rectangle>");var l=new LayoutEngine().Arrange(r);var p=l.Entries[1].WorldTransform.Map(new(10,10));Near(60,p.X);Near(10,p.Y);});
Test("animation no-op preserves original root",()=>{var r=Root(Node("Rectangle","A"));Check(ReferenceEquals(r,AnimationEngine.Evaluate(r,null,0)));});
Test("animation coalesces several properties per node",()=>{var n=Node("Rectangle","A");var r=Root(n);var board=new DesignStoryboard(Guid.NewGuid(),"B",1,[new(n.Id,"Width",[new(0,50),new(1,100)]),new(n.Id,"Height",[new(0,30),new(1,90)])]);var p=AnimationEngine.Evaluate(r,board,.5).Find(n.Id)!;Near(75,p.Number("Width"));Near(60,p.Number("Height"));});
Test("key replacement preserves track ordering",()=>{var a=Guid.NewGuid();var b=Guid.NewGuid();var board=new DesignStoryboard(Guid.NewGuid(),"B",1,[new(a,"Width",[new(0,20)]),new(b,"Opacity",[new(0,1)])]);board=AnimationEngine.SetKey(board,a,"Width",.5,50);Equal(a,board.Tracks[0].TargetId);});
Test("state is the animation base when first key is delayed",()=>{var n=Node("Rectangle","A").Set("Opacity",1);var r=Root(n);var board=new DesignStoryboard(Guid.NewGuid(),"B",1,[new(n.Id,"Opacity",[new(1,1)])]);var state=new DesignState("Dim",[new(n.Id,"Opacity","0")]);Near(.5,AnimationEngine.Evaluate(r,board,.5,state).Find(n.Id)!.Number("Opacity"));});
Test("invalid native markup rejected before rendering",()=>{var d=new DesignDocument { Root=Root() with { PropertyElements=["<Canvas.Resources>"] } };Reject(()=>DocumentValidator.Validate(d));});
Test("duplicate storyboards rejected",()=>{var b=new DesignStoryboard(Guid.NewGuid(),"Same",1,[]);Reject(()=>DocumentValidator.Validate(new(){Root=Root(),Storyboards=[b,b with { Id=Guid.NewGuid() }]}));});
Test("implicit style applies while local values win",()=>{var root=Parse("<Canvas.Resources><Style TargetType='Button'><Setter Property='Background' Value='Red'/><Setter Property='Foreground' Value='White'/></Style></Canvas.Resources><Button x:Name='A' Width='100' Height='30'/><Button x:Name='B' Width='100' Height='30' Background='Blue'/>");var preview=DesignPreview.Get(root);Equal(0,preview.Diagnostics.Count);Equal("Red",preview.Root.Children[0].Get("Background"));Equal("Blue",preview.Root.Children[1].Get("Background"));});
Test("BasedOn and local resource scopes",()=>{var root=Parse("<Canvas.Resources><Style x:Key='Base' TargetType='Button'><Setter Property='Foreground' Value='Red'/></Style><Style x:Key='Derived' TargetType='Button' BasedOn='{StaticResource Base}'><Setter Property='Background' Value='Blue'/></Style></Canvas.Resources><Button x:Name='A' Width='100' Height='30' Style='{StaticResource Derived}'/>");var n=DesignPreview.Resolve(root).Children[0];Equal("Red",n.Get("Foreground"));Equal("Blue",n.Get("Background"));});
Test("template expansion is deterministic and non-mutating",()=>{var n=Node("Button","A",0,0,120,40).Set("Content","Template text").Set("Background","Red");var d=TemplateLibrary.Save(new(){Root=Root(n)},TemplateLibrary.CreateDefault());d=TemplateLibrary.Apply(d,[n.Id],"ButtonTemplate");var p=DesignPreview.Get(d.Root);Equal(0,p.Diagnostics.Count);Check(d.Root.Children[0].Children.IsEmpty);var visual=p.Root.Children[0].Children[0];Equal("Red",visual.Get("Background"));Check(p.Root.DescendantsAndSelf().Any(c=>c.Get("Text")=="Template text"));Equal(visual.Id,DesignPreview.Get(d.Root).Root.Children[0].Children[0].Id);});
Test("invalid template save is atomic",()=>{var d=new DesignDocument { Root=Root() };Reject(()=>TemplateLibrary.Save(d,"<ControlTemplate/>"));Check(d.Root.PropertyElements.IsEmpty);});
Test("cyclic styles report diagnostics without executing",()=>{var r=Parse("<Canvas.Resources><Style x:Key='A' BasedOn='{StaticResource B}'/><Style x:Key='B' BasedOn='{StaticResource A}'/></Canvas.Resources><Button Style='{StaticResource A}'/>");Check(DesignPreview.Get(r).Diagnostics.Count>0);});
Test("shaped text cache avoids shaping unchanged runs",()=>{using var text=new SkiaTextService();var a=text.Measure("office fi ffi",20,"sans-serif");var count=text.ShapeCount;var b=text.Measure("office fi ffi",20,"sans-serif");Near(a.Width,b.Width);Equal(count,text.ShapeCount);Check(text.CacheHits>0);});
Test("wrapping measures multiple lines",()=>{using var text=new SkiaTextService();var single=text.Measure("A paragraph that wraps across several lines.",18,"sans-serif");var wrapped=text.Measure("A paragraph that wraps across several lines.",18,"sans-serif",95,true);Check(wrapped.Height>single.Height);Check(wrapped.Width<=96);});
Test("combining characters can wrap without invalid text",()=>{using var text=new SkiaTextService();var size=text.Measure("e\u0301e\u0301e\u0301e\u0301",20,"sans-serif",15,true);Check(size.Height>20);});
byte[] ImageBytes() { using var surface=SKSurface.Create(new SKImageInfo(8,8));surface.Canvas.Clear(SKColors.Lime);using var image=surface.Snapshot();using var bytes=image.Encode(SKEncodedImageFormat.Png,100);return bytes.ToArray(); }
Test("embedded raster decode is cached",()=>{using var images=new EmbeddedImages();var source=EmbeddedImages.CreateSource(ImageBytes());var a=images.Get(source,out var error);Check(error is null&&a is not null);Check(ReferenceEquals(a,images.Get(source,out _)));Equal(1L,images.DecodeCount);});
Test("external images remain non-executing",()=>{using var images=new EmbeddedImages();Check(images.Get("https://example.invalid/image.png",out var error) is null);Check(error is not null);});
Test("invalid image is diagnosed without crashing",()=>{using var images=new EmbeddedImages();Check(images.Get("data:image/png;base64,AA==",out var error) is null);Check(error is not null);});
Test("rendering and PNG export include image pixels",()=>{var source=EmbeddedImages.CreateSource(ImageBytes());var n=Node("Image","Image",10,10,80,80).Set("Source",source);using var renderer=new DesignRenderer();var layout=new LayoutEngine(renderer).Arrange(Root(n));var png=renderer.ExportPng(layout,1);using var bitmap=SKBitmap.Decode(png);var pixel=bitmap.GetPixel(30,30);Check(pixel.Green>200&&pixel.Red<20);renderer.ExportPng(layout,1);Equal(1L,renderer.ImageDecodeCount);});
Test("transformed renderer uses the same matrix as picking",()=>{var n=Node("Rectangle","R",10,10,30,30).Set("Fill","Red");var p=Node("Canvas","P",100,100,100,100) with { Rotation=90,Children=[n] };using var renderer=new DesignRenderer();var layout=new LayoutEngine(renderer).Arrange(Root(p));var e=layout.ById[n.Id];var center=e.WorldTransform.Map(e.Bounds.Center);using var bitmap=SKBitmap.Decode(renderer.ExportPng(layout,1));Check(bitmap.GetPixel((int)center.X,(int)center.Y).Red>200);Equal(n.Id,layout.HitTest(center)!.Node.Id);});
Test("second render reuses shaped glyph cache",()=>{var n=Node("TextBlock","T",0,0,300,50).Set("Text","Cached typography");using var renderer=new DesignRenderer();var layout=new LayoutEngine(renderer).Arrange(Root(n));renderer.ExportPng(layout,1);var count=renderer.TextShapeCount;renderer.ExportPng(layout,1);Equal(count,renderer.TextShapeCount);});
Test("expanded template renders into PNG",()=>{var n=Node("Button","A",10,10,120,40).Set("Content","Hello").Set("Background","Red");var d=TemplateLibrary.Save(new(){Root=Root(n)},TemplateLibrary.CreateDefault());d=TemplateLibrary.Apply(d,[n.Id],"ButtonTemplate");using var renderer=new DesignRenderer();var layout=new LayoutEngine(renderer).Arrange(DesignPreview.Resolve(d.Root));using var bitmap=SKBitmap.Decode(renderer.ExportPng(layout,1));Check(bitmap.GetPixel(15,20).Red>200);});


Test("wrapped line layout is cached independently of glyph shaping",()=>{using var text=new SkiaTextService();text.Measure("A cached paragraph with several lines and words.",18,"sans-serif",100,true);var count=text.LineLayoutCount;for(var i=0;i<100;i++)text.Measure("A cached paragraph with several lines and words.",18,"sans-serif",100,true);Equal(count,text.LineLayoutCount);Check(text.LineCacheHits>=100);});
Test("width change invalidates only its line layout key",()=>{using var text=new SkiaTextService();var a=text.Measure("A paragraph with more than a few words for wrapping.",18,"sans-serif",100,true);var count=text.LineLayoutCount;var b=text.Measure("A paragraph with more than a few words for wrapping.",18,"sans-serif",200,true);Equal(count+1,text.LineLayoutCount);Check(b.Height<a.Height);});
Test("hot glyphs survive churn beyond cache capacity",()=>{using var text=new SkiaTextService();for(var i=0;i<800;i++){text.Measure("Frequently drawn label",18,"sans-serif");text.Measure("Changing label "+i,18,"sans-serif");}var count=text.ShapeCount;text.Measure("Frequently drawn label",18,"sans-serif");Equal(count,text.ShapeCount);Check(text.CachedRunBytes<=8*1024*1024);Check(text.CachedLineBytes<=2*1024*1024);});
Test("styled measurement honors line height",()=>{using var text=new SkiaTextService();var n=Node("TextBlock","T").Set("Text","First\nSecond").Set("LineHeight","35").Set("FontWeight","Bold");Near(70,text.Measure(n,400).Height);});
Test("layout uses the renderer's styled text metrics",()=>{using var renderer=new DesignRenderer();var n=new DesignNode{Type="TextBlock"}.Set(DesignNode.NameKey,"T").Set("Text","First\nSecond").Set("LineHeight","35").Set("FontWeight","Bold");var l=new LayoutEngine(renderer).Arrange(Root(n));Near(70,l.ById[n.Id].Bounds.Height);});
Test("repainting avoids rewrapping a warm paragraph",()=>{var n=Node("TextBlock","T",10,10,130,200).Set("Text","A wrapped paragraph rendered more than once.").Set("TextWrapping","Wrap");using var renderer=new DesignRenderer();var layout=new LayoutEngine(renderer).Arrange(Root(n));renderer.ExportPng(layout,1);var count=renderer.TextLayoutCount;renderer.ExportPng(layout,1);Equal(count,renderer.TextLayoutCount);});
Test("recorded state brush overrides base inline gradient pixels",()=>{var root=Parse("<Rectangle x:Name='R' Width='40' Height='40'><Rectangle.Fill><LinearGradientBrush><GradientStop Offset='0' Color='Blue'/><GradientStop Offset='1' Color='White'/></LinearGradientBrush></Rectangle.Fill></Rectangle>");var id=root.Children[0].Id;var state=new DesignState("Active",[new(id,"Fill","Red")]);using var renderer=new DesignRenderer();var layout=new LayoutEngine(renderer).Arrange(AnimationEngine.EvaluateLocal(root,null,0,state));using var bitmap=SKBitmap.Decode(renderer.ExportPng(layout,1));Check(bitmap.GetPixel(20,20).Red>240&&bitmap.GetPixel(20,20).Blue<10);});

var nodes=Enumerable.Range(0,2000).Select(i=>Node("Rectangle","R"+i,i%100*3,i/100*3,2,2)).ToImmutableArray();
var large=Root() with { Children=nodes };var tracks=nodes.Take(40).Select(n=>new AnimationTrack(n.Id,"Opacity",[new(0,0),new(1,1)])).ToImmutableArray();
var animation=new DesignStoryboard(Guid.NewGuid(),"Bench",1,tracks);
AnimationEngine.Evaluate(large,animation,.25);
(long Bytes,double Ms) Bench(Func<DesignNode> run)
{
    GC.Collect();var allocated=GC.GetAllocatedBytesForCurrentThread();var start=Stopwatch.GetTimestamp();
    for(var i=0;i<5;i++) _=run();return(GC.GetAllocatedBytesForCurrentThread()-allocated,Stopwatch.GetElapsedTime(start).TotalMilliseconds);
}
var batch=Bench(()=>AnimationEngine.Evaluate(large,animation,.5));
var sequential=Bench(()=>{var r=large;foreach(var t in tracks) r=AnimationEngine.Apply(r,t.TargetId,t.Property,"0.5");return r;});
Directory.CreateDirectory("artifacts/verification");
File.WriteAllText("artifacts/verification/performance.json",JsonSerializer.Serialize(new { description="CPU-only five-iteration comparison; not a GPU or browser benchmark",nodes=2000,tracks=40,batchBytes=batch.Bytes,sequentialBytes=sequential.Bytes,batchMilliseconds=batch.Ms,sequentialMilliseconds=sequential.Ms },new JsonSerializerOptions { WriteIndented=true }));
Console.WriteLine($"BATCH {batch.Bytes} bytes / {batch.Ms:F3}ms; SEQUENTIAL {sequential.Bytes} bytes / {sequential.Ms:F3}ms");
Console.WriteLine($"{passed} passed; {failed} failed.");return failed==0 ? 0 : 1;
