using System.Text.Json.Nodes;
using System.Collections.Immutable;
using DesignSpace.Animation;
using DesignSpace.Core;
using DesignSpace.Engine;
using DesignSpace.Xaml;

internal static class StateTransitionTests
{
    public static (int Passed,int Failed) Run()
    {
        var passed=0;var failed=0;
        void Test(string name,Action action){try{action();passed++;Console.WriteLine("PASS state groups: "+name);}catch(Exception e){failed++;Console.Error.WriteLine("FAIL state groups: "+name+": "+e);}}
        void Check(bool value){if(!value)throw new Exception("Assertion failed");}
        void Near(double a,double b){if(Math.Abs(a-b)>1e-7)throw new Exception($"Expected {a}, got {b}");}
        void Reject(Action action){try{action();}catch{return;}throw new Exception("Expected rejection");}
        DesignDocument Fixture()
        {
            var n=DesignNode.Create("Rectangle","Box",10,20,100,80).Set("Opacity",1).Set("Fill","#FF000000");
            return new(){Root=DesignNode.Create("Canvas","Root") with{Children=[n]},States=[
                new("Normal",[new(n.Id,"Opacity","1"),new(n.Id,"Fill","#FF000000")]){Group="Common"},
                new("Pressed",[new(n.Id,"Opacity","0.2"),new(n.Id,"Fill","#FFFFFFFF")]){Group="Common"},
                new("Focused",[new(n.Id,"Width","200")]){Group="Focus"}],StateGroups=[new("Common",[new(null,null,2)]),new("Focus",[new(null,null,1)])]};
        }
        DesignNode At(DesignDocument d,VisualStatePreview p,double time)=>AnimationEngine.EvaluateLocal(d.Root,null,0,p.Sample(time)).Children[0];
        string Wrap(string content)=>"<Canvas xmlns='http://schemas.microsoft.com/winfx/2006/xaml/presentation' xmlns:x='http://schemas.microsoft.com/winfx/2006/xaml'>"+content+"<Rectangle x:Name='Box' Width='100' Height='80'/></Canvas>";
        string Group(string content)=>"<VisualStateManager.VisualStateGroups><VisualStateGroup x:Name='Common'>"+content+"</VisualStateGroup></VisualStateManager.VisualStateGroups>";
        Test("legacy states retain their default group",()=>{var json=JsonNode.Parse(NativeDocumentCodec.Write(Fixture()))!.AsObject();json.Remove("stateGroups");foreach(var state in json["states"]!.AsArray())state!.AsObject().Remove("group");var d=NativeDocumentCodec.Read(json.ToJsonString());Check(d.StateGroups.IsEmpty&&d.States.All(s=>s.Group==VisualStateGroups.DefaultName));Check(VisualStateGroups.Get(d).Single().Name==VisualStateGroups.DefaultName);Check(d.Root.Children[0].Get("Width")=="100");});
        Test("explicit null metadata is not migrated into valid data",()=>{var json=JsonNode.Parse(NativeDocumentCodec.Write(Fixture()))!.AsObject();json["stateGroups"]=null;Reject(()=>NativeDocumentCodec.Read(json.ToJsonString()));json=JsonNode.Parse(NativeDocumentCodec.Write(Fixture()))!.AsObject();json["states"]!.AsArray()[0]!["group"]=null;Reject(()=>NativeDocumentCodec.Read(json.ToJsonString()));});
        Test("declared and implicit groups retain order",()=>{var d=Fixture();d=d with{StateGroups=[new("Empty",[])]};Check(VisualStateGroups.Get(d).Select(g=>g.Name).SequenceEqual(new[]{"Empty","Common","Focus"}));});
        Test("native groups and rules survive reflection-free persistence",()=>{var d=Fixture();var json=NativeDocumentCodec.Write(d);Check(NativeDocumentCodec.Write(NativeDocumentCodec.Read(json))==json);});
        Test("XAML groups, memberships and easing roundtrip",()=>{var d=StateGroupEditing.SetTransition(Fixture(),"Common",new("Normal","Pressed",.375,"EaseOut"));var x=XamlCodec.Write(d);var parsed=XamlCodec.Parse(x).Document;Check(parsed.StateGroups.Length==2&&parsed.States.Single(s=>s.Name=="Focused").Group=="Focus");var t=parsed.StateGroups[0].Transitions.Last();Near(.375,t.Duration);Check(t.From=="Normal"&&t.To=="Pressed"&&t.Easing=="EaseOut");});
        Test("empty group survives XAML",()=>Check(XamlCodec.Parse(XamlCodec.Write(StateGroupEditing.AddGroup(DesignDocument.Empty(),"Empty"))).Document.StateGroups.Single().Name=="Empty"));
        Test("state reconciliation retains target identities",()=>{var d=Fixture();var result=XamlCodec.Reconcile(d,XamlCodec.Parse(XamlCodec.Write(d)).Document);Check(result.States[1].Setters[0].TargetId==d.Root.Children[0].Id);Check(result.StateGroups[0].Name=="Common");});
        Test("pair transition outranks all wildcards",()=>{var g=new DesignStateGroup("Common",[new(null,null,4),new("Normal",null,3),new(null,"Pressed",2),new("Normal","Pressed",1)]);Near(1,VisualStateGroups.Match(g,"Normal","Pressed")!.Duration);});
        Test("destination outranks source",()=>{var g=new DesignStateGroup("Common",[new("Normal",null,3),new(null,"Pressed",2)]);Near(2,VisualStateGroups.Match(g,"Normal","Pressed")!.Duration);});
        Test("source transition used when destination does not match",()=>{var g=new DesignStateGroup("Common",[new("Normal",null,3),new(null,"Focused",2)]);Near(3,VisualStateGroups.Match(g,"Normal","Pressed")!.Duration);});
        Test("default transition is fallback",()=>{var g=new DesignStateGroup("Common",[new(null,null,4),new("Normal","Pressed",1)]);Near(4,VisualStateGroups.Match(g,null,"Normal")!.Duration);});
        Test("no matching rule means no animation",()=>{var d=Fixture() with{StateGroups=[new("Common",[])]};var p=new VisualStatePreview(d);p.GoToState("Pressed",0);Check(!p.IsRunning(0));Near(.2,At(d,p,0).Number("Opacity"));});
        Test("unknown state rejected before mutation",()=>{var p=new VisualStatePreview(Fixture());Reject(()=>p.GoToState("Missing",0));Check(p.ActiveStates.Count==0);});
        Test("negative and nonfinite sample times rejected",()=>{var p=new VisualStatePreview(Fixture());Reject(()=>p.Sample(-1));Reject(()=>p.Sample(double.NaN));Reject(()=>p.GoToState("Normal",double.PositiveInfinity));});
        Test("host state changes use monotonic time",()=>{var p=new VisualStatePreview(Fixture());p.GoToState("Normal",1);Reject(()=>p.GoToState("Pressed",.5));Check(p.ActiveStates["Common"]=="Normal");});
        Test("numeric values interpolate without changing base",()=>{var d=Fixture();var original=NativeDocumentCodec.Write(d);var p=new VisualStatePreview(d);p.GoToState("Normal",0,false);p.GoToState("Pressed",0);Near(.6,At(d,p,1).Number("Opacity"));Check(p.IsRunning(1));Near(.2,At(d,p,2).Number("Opacity"));Check(!p.IsRunning(2));Check(NativeDocumentCodec.Write(d)==original);});
        Test("solid colors interpolate ARGB channels",()=>{var d=Fixture();var p=new VisualStatePreview(d);p.GoToState("Normal",0,false);p.GoToState("Pressed",0);Check(At(d,p,1).Get("Fill")=="#FF808080");});
        Test("named and short hex colors interpolate",()=>{var d=Fixture();d=d with{States=[new("A",[new(d.Root.Children[0].Id,"Fill","Red")]){Group="Common"},new("B",[new(d.Root.Children[0].Id,"Fill","#00F")]){Group="Common"}]};var p=new VisualStatePreview(d);p.GoToState("A",0,false);p.GoToState("B",0);Check(At(d,p,1).Get("Fill")=="#FF800080");});
        Test("alpha channels interpolate",()=>{var d=Fixture();d=d with{States=[new("Fade",[new(d.Root.Children[0].Id,"Fill","#00000000")]){Group="Common"}]};var p=new VisualStatePreview(d);p.GoToState("Fade",0);Check(At(d,p,1).Get("Fill")=="#80000000");});
        Test("scRGB endpoints resolve once",()=>{var d=Fixture();d=d with{States=[new("White",[new(d.Root.Children[0].Id,"Fill","sc#1,1,1")]){Group="Common"}]};var p=new VisualStatePreview(d);p.GoToState("White",0);Check(At(d,p,1).Get("Fill")=="#FF808080");});
        foreach(var easing in new[]{"EaseIn","EaseOut","EaseInOut"})Test("generated cubic "+easing,()=>{var d=StateGroupEditing.SetTransition(Fixture(),"Common",new(null,null,2,easing));var p=new VisualStatePreview(d);p.GoToState("Normal",0,false);p.GoToState("Pressed",0);Near(1-.8*AnimationEngine.Ease(.25,easing),At(d,p,.5).Number("Opacity"));});
        Test("interrupted transition starts from its current value",()=>{var d=Fixture();var p=new VisualStatePreview(d);p.GoToState("Normal",0,false);p.GoToState("Pressed",0);Near(.6,At(d,p,1).Number("Opacity"));p.GoToState("Normal",1);Near(.6,At(d,p,1).Number("Opacity"));Near(.8,At(d,p,2).Number("Opacity"));Near(1,At(d,p,3).Number("Opacity"));});
        Test("reselecting active destination does not restart transition",()=>{var p=new VisualStatePreview(Fixture());p.GoToState("Pressed",0);Check(!p.GoToState("Pressed",1));Check(!p.IsRunning(2));});
        Test("independent groups animate concurrently",()=>{var d=Fixture();var p=new VisualStatePreview(d);p.GoToState("Pressed",0);p.GoToState("Focused",.5);var n=At(d,p,1);Near(.6,n.Number("Opacity"));Near(150,n.Number("Width"));Check(p.ActiveStates.Count==2);});
        Test("one group's Base leaves other groups active",()=>{var d=Fixture();var p=new VisualStatePreview(d);p.GoToState("Pressed",0,false);p.GoToState("Focused",0,false);p.GoToBase("Common",1,false);Near(1,At(d,p,1).Number("Opacity"));Near(200,At(d,p,1).Number("Width"));Check(p.ActiveStates.Count==1);});
        Test("return to Base interpolates then removes the overlay",()=>{var d=Fixture();var p=new VisualStatePreview(d);p.GoToState("Pressed",0,false);p.GoToBase("Common",1);Near(.6,At(d,p,2).Number("Opacity"));Check(p.Sample(3) is null);});
        Test("omitted target setter returns to base",()=>{var d=Fixture();d=d with{States=d.States.Add(new("Empty",[]){Group="Common"})};var p=new VisualStatePreview(d);p.GoToState("Pressed",0,false);p.GoToState("Empty",1);Near(.6,At(d,p,2).Number("Opacity"));Near(1,At(d,p,3).Number("Opacity"));});
        Test("non-interpolatable values switch at completion",()=>{var d=Fixture();var id=d.Root.Children[0].Id;d=d with{Root=d.Root.Update(id,n=>n.Set("Visibility","Visible")),States=[new("Hidden",[new(id,"Visibility","Collapsed")]){Group="Common"}]};var p=new VisualStatePreview(d);p.GoToState("Hidden",0);Check(At(d,p,1).Get("Visibility")=="Visible");Check(At(d,p,2).Get("Visibility")=="Collapsed");});
        Test("Auto size is not converted to zero",()=>{var d=Fixture();var id=d.Root.Children[0].Id;d=d with{Root=d.Root.Update(id,n=>n.Set("Width","Auto"))};var p=new VisualStatePreview(d);p.GoToState("Focused",0);Check(At(d,p,.5).Get("Width")=="Auto");Near(200,At(d,p,1).Number("Width"));});
        Test("style/resource resolution happens only during transition compilation",()=>{var d=Fixture();var calls=0;var p=new VisualStatePreview(d,n=>{calls++;return n;});p.GoToState("Pressed",0);var initial=calls;for(var i=0;i<100;i++)p.Sample(i*.01);Check(calls==initial&&initial==2);});
        Test("resource-backed state color animates",()=>{var d=Fixture();d=d with{Root=d.Root with{PropertyElements=["<Canvas.Resources xmlns='http://schemas.microsoft.com/winfx/2006/xaml/presentation' xmlns:x='http://schemas.microsoft.com/winfx/2006/xaml'><SolidColorBrush x:Key='White' Color='White'/></Canvas.Resources>"]}};d=StateEditing.SetProperty(d,"Pressed",[d.Root.Children[0].Id],"Fill","{StaticResource White}");var p=new VisualStatePreview(d,DesignPreview.Resolve);p.GoToState("Pressed",0);Check(At(d,p,1).Get("Fill")=="#FF808080");});
        Test("inline solid brush can be the base endpoint",()=>{var d=Fixture();var id=d.Root.Children[0].Id;d=d with{Root=d.Root.Update(id,n=>n with{Properties=n.Properties.Remove("Fill"),PropertyElements=["<Rectangle.Fill xmlns='http://schemas.microsoft.com/winfx/2006/xaml/presentation'><SolidColorBrush Color='Black'/></Rectangle.Fill>"]})};var p=new VisualStatePreview(d);p.GoToState("Pressed",0);Check(At(d,p,1).Get("Fill")=="#FF808080");});
        Test("conflicting active group properties reject atomically",()=>{var d=Fixture();d=d with{States=d.States.Add(new("Conflict",[new(d.Root.Children[0].Id,"Opacity",".5")]){Group="Focus"})};var p=new VisualStatePreview(d);p.GoToState("Pressed",0);Reject(()=>p.GoToState("Conflict",1));Check(p.ActiveStates.Count==1);Near(.6,At(d,p,1).Number("Opacity"));});
        Test("inactive group does not reserve properties forever",()=>{var d=Fixture();d=d with{States=d.States.Add(new("Conflict",[new(d.Root.Children[0].Id,"Opacity",".5")]){Group="Focus"})};var p=new VisualStatePreview(d);p.GoToState("Pressed",0,false);p.GoToBase("Common",0,false);p.GoToState("Conflict",0,false);Near(.5,At(d,p,0).Number("Opacity"));});
        Test("repeated samples reuse overlay",()=>{var p=new VisualStatePreview(Fixture());p.GoToState("Pressed",0);Check(ReferenceEquals(p.Sample(.5),p.Sample(.5)));Check(ReferenceEquals(p.Sample(3),p.Sample(4)));});
        Test("complete and reset do not mutate document",()=>{var d=Fixture();var p=new VisualStatePreview(d);p.GoToState("Pressed",0);p.Complete();Check(!p.IsRunning(.5));Near(.2,At(d,p,.5).Number("Opacity"));p.Reset();Check(p.ActiveStates.Count==0&&p.Sample(0) is null);Near(1,d.Root.Children[0].Number("Opacity"));});
        Test("transition frames do not create history",()=>{var d=Fixture();var session=new DesignSession(d);var p=new VisualStatePreview(d);p.GoToState("Pressed",0);for(var i=0;i<100;i++)p.Sample(i*.03);Check(session.Revision==0&&ReferenceEquals(session.Document,d));});
        Test("completed preview has bounded idle allocations",()=>{var p=new VisualStatePreview(Fixture());p.GoToState("Pressed",0);_=p.Sample(3);var start=GC.GetAllocatedBytesForCurrentThread();for(var i=0;i<1000;i++)p.Sample(4+i);var bytes=GC.GetAllocatedBytesForCurrentThread()-start;Check(bytes<4096);Console.WriteLine("STATE IDLE allocated bytes: "+bytes);});
        Test("rename state updates both transition selectors",()=>{var d=StateGroupEditing.SetTransition(Fixture(),"Common",new("Pressed","Pressed",1));d=StateGroupEditing.RenameState(d,"Pressed","Down");Check(d.States.Any(s=>s.Name=="Down")&&d.StateGroups[0].Transitions.Last().From=="Down"&&d.StateGroups[0].Transitions.Last().To=="Down");});
        Test("delete state removes referencing transitions but keeps default",()=>{var d=StateGroupEditing.SetTransition(Fixture(),"Common",new(null,"Pressed",1));d=StateGroupEditing.RemoveState(d,"Pressed");Check(d.StateGroups[0].Transitions.Length==1&&d.StateGroups[0].Transitions[0].To is null);});
        Test("rename group retains memberships and transition references",()=>{var d=StateGroupEditing.RenameGroup(Fixture(),"Common","Pointer");Check(d.States[0].Group=="Pointer"&&d.StateGroups[0].Name=="Pointer");});
        Test("delete group removes only its member states",()=>{var d=StateGroupEditing.RemoveGroup(Fixture(),"Common");Check(d.States.Single().Name=="Focused"&&d.StateGroups.Single().Name=="Focus");});
        Test("group/state changes are one undoable transaction",()=>{var d=Fixture();var s=new DesignSession(d);s.Execute("Rename",p=>StateGroupEditing.RenameGroup(p,"Common","Pointer"));Check(s.Revision==1);s.Undo();Check(ReferenceEquals(s.Document,d));});
        Test("same transition update is a true no-op",()=>{var d=Fixture();Check(ReferenceEquals(d,StateGroupEditing.SetTransition(d,"Common",new(null,null,2))));});
        Test("unknown group and cross-group selectors rejected",()=>{var d=Fixture();Reject(()=>StateGroupEditing.SetTransition(d,"Missing",new(null,null,1)));Reject(()=>StateGroupEditing.SetTransition(d,"Common",new(null,"Focused",1)));});
        Test("duplicate state and group names rejected",()=>{var d=Fixture();Reject(()=>StateGroupEditing.AddGroup(d,"Common"));Reject(()=>StateGroupEditing.AddState(d,"Focus","Pressed"));Reject(()=>StateGroupEditing.RenameGroup(d,"Common","Focus"));});
        Test("invalid transition duration and easing rejected",()=>{foreach(var value in new[]{-1d,double.NaN,double.PositiveInfinity,86401})Reject(()=>StateGroupEditing.SetTransition(Fixture(),"Common",new(null,null,value)));Reject(()=>StateGroupEditing.SetTransition(Fixture(),"Common",new(null,null,1,"Unknown")));});
        Test("null and duplicate group definitions rejected",()=>{var d=Fixture();Reject(()=>DocumentValidator.Validate(d with{StateGroups=default}));Reject(()=>DocumentValidator.Validate(d with{StateGroups=[d.StateGroups[0],d.StateGroups[0]]}));});
        Test("duplicate selector pairs rejected",()=>{var d=Fixture();Reject(()=>DocumentValidator.Validate(d with{StateGroups=[new("Common",[new(null,null,1),new(null,null,2)])]}));});
        Test("nonstandard group name imports as editable",()=>{var d=XamlCodec.Parse(Wrap(Group("<VisualState x:Name='Normal'/>"))).Document;Check(d.States.Single().Group=="Common");});
        Test("explicit States wrapper imports",()=>{var d=XamlCodec.Parse(Wrap(Group("<VisualStateGroup.States><VisualState x:Name='Normal'/></VisualStateGroup.States>"))).Document;Check(d.States.Length==1);});
        foreach(var unsupported in new[]{
            "<VisualTransition GeneratedDuration='0:0:1'><Storyboard/></VisualTransition>",
            "<VisualTransition GeneratedDuration='Forever'/>",
            "<VisualTransition To='Missing' GeneratedDuration='0:0:1'/>",
            "<VisualTransition GeneratedDuration='0:0:1'><VisualTransition.GeneratedEasingFunction><BounceEase/></VisualTransition.GeneratedEasingFunction></VisualTransition>",
            "<VisualTransition GeneratedDuration='0:0:1' Custom='Keep'/>"})
            Test("unsupported transition keeps entire group "+unsupported,()=>{var content=Wrap(Group("<VisualState x:Name='Normal'/><VisualStateGroup.Transitions>"+unsupported+"</VisualStateGroup.Transitions>"));var result=XamlCodec.Parse(content);Check(result.Document.States.IsEmpty&&result.Document.StateGroups.IsEmpty&&result.Diagnostics.Any());Check(XamlCodec.Write(result.Document).Contains("VisualTransition"));});
        Test("state triggers preserve entire group",()=>{var result=XamlCodec.Parse(Wrap(Group("<VisualState x:Name='Normal'><VisualState.StateTriggers><AdaptiveTrigger MinWindowWidth='500'/></VisualState.StateTriggers></VisualState>")));Check(result.Document.States.IsEmpty&&XamlCodec.Write(result.Document).Contains("AdaptiveTrigger"));});
        Test("supported sibling group imports while unsupported one stays",()=>{var text=Wrap(Group("<VisualState x:Name='Normal'/>").Replace("</VisualStateManager.VisualStateGroups>","<VisualStateGroup x:Name='Other'><VisualState x:Name='Special'><Storyboard/></VisualState></VisualStateGroup></VisualStateManager.VisualStateGroups>"));var result=XamlCodec.Parse(text);Check(result.Document.States.Length==1&&XamlCodec.Write(result.Document).Contains("Special"));});
        Test("preserved group name conflict prevents destructive export",()=>{var d=XamlCodec.Parse(Wrap(Group("<VisualState x:Name='Normal'><Storyboard/></VisualState>"))).Document;d=StateGroupEditing.AddGroup(d,"Common");Reject(()=>XamlCodec.Write(d));});
        Test("malformed setters are not partially extracted",()=>{var result=XamlCodec.Parse(Wrap(Group("<VisualState x:Name='Normal'><VisualState.Setters><Setter Target='Box.Opacity' Value='.5'/><Setter Target='Missing.Opacity' Value='.4'/></VisualState.Setters></VisualState>")));Check(result.Document.States.IsEmpty&&XamlCodec.Write(result.Document).Contains("Missing.Opacity"));});
        Directory.CreateDirectory("artifacts/verification");File.WriteAllText("artifacts/verification/state-transition-results.json",$"{{\"passed\":{passed},\"failed\":{failed}}}");
        return(passed,failed);
    }
}
