using System.Collections.Immutable;
using System.Text.Json;
using DesignSpace.Core;
using DesignSpace.Engine;
using DesignSpace.Xaml;

internal static class WorkspaceTests
{
    public static (int Passed,int Failed) Run()
    {
        var passed=0;var failed=0;
        void Test(string name,Action run){try{run();passed++;Console.WriteLine("PASS workspace: "+name);}catch(Exception e){failed++;Console.Error.WriteLine("FAIL workspace: "+name+": "+e);}}
        void Check(bool condition){if(!condition)throw new Exception("Assertion failed");}
        void Reject(Action run){try{run();}catch{return;}throw new Exception("Expected rejection");}
        DocumentWorkspace Create()=>new(DesignDocument.Empty());
        Guid AddShape(DesignSession s)=>s.Add("Rectangle",new(20,30,40,50));
        Test("starts with one active document",()=>{using var w=Create();Check(w.Documents.Count==1&&w.ActiveDocumentId==w.Documents[0].Id);Check(!w.Active.IsDirty);});
        Test("new document does not replace existing geometry",()=>{using var w=Create();var first=w.ActiveDocumentId;var id=AddShape(w.Session);w.Add(DesignDocument.Empty(),"Second.designspace",true);Check(w.Documents.Count==2&&w.Active.IsDirty);w.Activate(first);Check(w.Session.Index.Find(id) is not null&&w.Session.CanUndo);});
        Test("one stable session serves every tab",()=>{using var w=Create();var s=w.Session;var id=w.ActiveDocumentId;w.Add(DesignDocument.Empty(),"Second.designspace");w.Activate(id);Check(ReferenceEquals(s,w.Session));});
        Test("histories are independent across documents",()=>{using var w=Create();var first=w.ActiveDocumentId;var a=AddShape(w.Session);var second=w.Add(DesignDocument.Empty(),"Second.designspace").Id;var b=AddShape(w.Session);w.Session.Undo();Check(w.Session.Index.Find(b) is null);w.Activate(first);Check(w.Session.Index.Find(a) is not null&&w.Session.CanUndo&&!w.Session.CanRedo);w.Session.Undo();Check(w.Session.Index.Find(a) is null);w.Activate(second);Check(w.Session.CanRedo);w.Session.Redo();Check(w.Session.Index.Find(b) is not null);});
        Test("redo ordering survives multiple tab switches",()=>{using var w=Create();var first=w.ActiveDocumentId;var a=AddShape(w.Session);var b=AddShape(w.Session);w.Session.Undo();w.Session.Undo();w.Add(DesignDocument.Empty(),"Second.designspace");w.Activate(first);w.Session.Redo();Check(w.Session.Index.Find(a) is not null&&w.Session.Index.Find(b) is null);w.Session.Redo();Check(w.Session.Index.Find(b) is not null);});
        Test("selection is retained independently",()=>{using var w=Create();var first=w.ActiveDocumentId;var a=AddShape(w.Session);w.Add(DesignDocument.Empty(),"Second.designspace");Check(w.Session.Selection.Count==0);w.Activate(first);Check(w.Session.Selection.SetEquals([a]));});
        Test("switches invalidate stale UI revision callbacks",()=>{using var w=Create();var first=w.ActiveDocumentId;var before=w.Session.Revision;w.Add(DesignDocument.Empty(),"Second.designspace");var middle=w.Session.Revision;w.Activate(first);Check(before<middle&&middle<w.Session.Revision);});
        Test("same-tab activation is a true no-op",()=>{using var w=Create();var rev=w.Session.Revision;Check(!w.Activate(w.ActiveDocumentId));Check(rev==w.Session.Revision);});
        Test("unknown tab activation is atomic",()=>{using var w=Create();var id=w.ActiveDocumentId;Reject(()=>w.Activate(Guid.NewGuid()));Check(w.ActiveDocumentId==id);});
        Test("savepoints survive tab switching",()=>{using var w=Create();var first=w.ActiveDocumentId;AddShape(w.Session);w.Session.MarkSaved();var saved=w.Session.Document;AddShape(w.Session);w.Add(DesignDocument.Empty(),"Second.designspace");w.Activate(first);Check(w.Active.IsDirty);w.Session.Undo();Check(!w.Active.IsDirty&&ReferenceEquals(saved,w.Session.Document));});
        Test("late save only marks the version actually written",()=>{using var w=Create();var id=w.ActiveDocumentId;AddShape(w.Session);var saved=w.Session.Document;AddShape(w.Session);w.MarkSaved(id,saved);Check(w.Active.IsDirty);w.Session.Undo();Check(!w.Active.IsDirty);});
        Test("late save cannot mark a different active tab clean",()=>{using var w=Create();var first=w.ActiveDocumentId;AddShape(w.Session);var saved=w.Session.Document;w.Add(DesignDocument.Empty(),"Second.designspace",true);w.MarkSaved(first,saved);Check(w.Active.IsDirty&&!w.Find(first).IsDirty);});
        Test("close refuses dirty documents without permission",()=>{using var w=Create();AddShape(w.Session);Reject(()=>w.Close(w.ActiveDocumentId));Check(w.Documents.Count==1&&w.Session.CanUndo);});
        Test("close refuses source drafts without permission",()=>{using var w=Create();w.UpdateEditor(w.ActiveDocumentId,new(){SourceDraft="<Broken"});Reject(()=>w.Close(w.ActiveDocumentId));});
        Test("close refuses unapplied auxiliary panel drafts",()=>{using var w=Create();w.UpdateEditor(w.ActiveDocumentId,new(){Panels=ImmutableDictionary<string,DesignerPanelDraft>.Empty.Add("Data",new(){HasChanges=true})});Reject(()=>w.Close(w.ActiveDocumentId));});
        Test("closing last document leaves a clean empty tab",()=>{using var w=Create();var old=w.ActiveDocumentId;Check(w.Close(old));Check(w.Documents.Count==1&&w.ActiveDocumentId!=old&&w.Session.Document.Root.Children.IsEmpty&&!w.Session.CanUndo);});
        Test("closing active chooses adjacent tab",()=>{using var w=Create();var first=w.ActiveDocumentId;var second=w.Add(DesignDocument.Empty(),"Second.designspace").Id;w.Close(second);Check(w.ActiveDocumentId==first&&w.Documents.Count==1);});
        Test("closing inactive does not change active document",()=>{using var w=Create();var first=w.ActiveDocumentId;var second=w.Add(DesignDocument.Empty(),"Second.designspace").Id;w.Close(first);Check(w.ActiveDocumentId==second);});
        Test("pinning is workspace metadata not document history",()=>{using var w=Create();var revision=w.Session.Revision;w.Pin(w.ActiveDocumentId,true);Check(w.Active.IsPinned&&w.Session.Revision==revision&&!w.Session.IsDirty);});
        Test("tab reorder retains active document and history",()=>{using var w=Create();var first=w.ActiveDocumentId;var second=w.Add(DesignDocument.Empty(),"Second.designspace").Id;AddShape(w.Session);w.Move(second,0);Check(w.Documents[0].Id==second&&w.ActiveDocumentId==second&&w.Session.CanUndo);Check(w.Documents[1].Id==first);});
        Test("tab position clamps to valid interval",()=>{using var w=Create();var first=w.ActiveDocumentId;w.Add(DesignDocument.Empty(),"Second.designspace");w.Move(first,99);Check(w.Documents[^1].Id==first);w.Move(first,-3);Check(w.Documents[0].Id==first);});
        Test("rename does not change document identity",()=>{using var w=Create();var id=w.ActiveDocumentId;var root=w.Session.Document.Root;w.Rename(id,"Renamed.designspace");Check(w.Active.FileName=="Renamed.designspace"&&ReferenceEquals(root,w.Session.Document.Root));});
        Test("rename rejects directory traversal",()=>{using var w=Create();Reject(()=>w.Rename(w.ActiveDocumentId,"../bad.designspace"));Check(w.Active.FileName=="MainPage.designspace");});
        Test("rename rejects filename collisions case-insensitively",()=>{using var w=Create();w.Add(DesignDocument.Empty(),"Second.designspace");Reject(()=>w.Rename(w.ActiveDocumentId,"mainpage.designspace"));});
        Test("unique filenames avoid existing tabs",()=>{using var w=Create();w.Add(DesignDocument.Empty(),"Page1.designspace");Check(w.UniqueFileName()=="Page2.designspace");});
        Test("source draft and conflict flag are independent per tab",()=>{using var w=Create();var first=w.ActiveDocumentId;w.UpdateEditor(first,new(){SourceDraft="<Invalid",DraftMatchesDesign=false});w.Add(DesignDocument.Empty(),"Second.designspace");Check(w.Active.Editor.SourceDraft is null);w.Activate(first);Check(w.Active.Editor.SourceDraft=="<Invalid"&&!w.Active.Editor.DraftMatchesDesign);});
        Test("viewport and split preferences persist in snapshot",()=>{using var w=Create();w.UpdateEditor(w.ActiveDocumentId,new(){Mode="Split",SplitOrientation="Horizontal",SplitRatio=.7,Zoom=1.2,PanX=-42,PanY=18,ShowGrid=true,HasViewport=true});var state=w.Capture().Documents[0].Editor;Check(state.SplitOrientation=="Horizontal"&&state.SplitRatio==.7&&state.PanX==-42&&state.ShowGrid);});
        Test("workspace JSON works without reflection",()=>{using var w=Create();AddShape(w.Session);w.Add(SampleDocument.Create(),"Sample.designspace");var text=WorkspaceCodec.Write(w.Capture());var restored=WorkspaceCodec.Read(text);Check(restored.Documents.Length==2&&restored.ActiveDocumentId==w.ActiveDocumentId);Check(WorkspaceCodec.Write(restored)==text);});
        Test("workspace JSON preserves invalid source instead of applying it",()=>{using var w=Create();w.UpdateEditor(w.ActiveDocumentId,new(){SourceDraft="<!DOCTYPE broken [<",DraftMatchesDesign=false});var restored=WorkspaceCodec.Read(WorkspaceCodec.Write(w.Capture()));Check(restored.Documents[0].Editor.SourceDraft=="<!DOCTYPE broken [<"&&restored.Documents[0].Document.Root.Type=="Canvas");});
        Test("workspace JSON preserves native shapes, states and animation",()=>{using var w=new DocumentWorkspace(SampleDocument.Create());var expected=w.Session.Document;var actual=WorkspaceCodec.Read(WorkspaceCodec.Write(w.Capture())).Documents[0].Document;Check(actual.Root.Id==expected.Root.Id&&actual.Storyboards.Length==expected.Storyboards.Length&&actual.States.Length==expected.States.Length);});
        Test("auxiliary draft fields and original values roundtrip",()=>{using var w=Create();var panel=new DesignerPanelDraft{Values=ImmutableDictionary<string,string>.Empty.Add("StrokeDashArray","0 0"),Originals=ImmutableDictionary<string,string>.Empty.Add("StrokeDashArray","2 2"),HasChanges=true,MatchesDesign=false};w.UpdateEditor(w.ActiveDocumentId,new(){Panels=ImmutableDictionary<string,DesignerPanelDraft>.Empty.Add("Stroke",panel)});var r=WorkspaceCodec.Read(WorkspaceCodec.Write(w.Capture())).Documents[0].Editor.Panels["Stroke"];Check(r.Values["StrokeDashArray"]=="0 0"&&r.Originals["StrokeDashArray"]=="2 2"&&r.HasChanges&&!r.MatchesDesign);});
        Test("recovery retains dirty flags but not undo stacks",()=>{using var w=Create();AddShape(w.Session);var restored=WorkspaceCodec.Read(WorkspaceCodec.Write(w.Capture()));w.Replace(restored);Check(w.Active.IsDirty&&!w.Session.CanUndo);});
        Test("workspace restore retains clean savepoint",()=>{using var w=Create();AddShape(w.Session);w.Session.MarkSaved();w.Replace(WorkspaceCodec.Read(WorkspaceCodec.Write(w.Capture())));Check(!w.Active.IsDirty);});
        Test("workspace restore is atomic for invalid hidden documents",()=>{using var w=Create();var before=w.Session.Document;var id=w.ActiveDocumentId;var file=new WorkspaceFile(Guid.NewGuid(),DesignDocument.Empty() with{FormatVersion=99},"Invalid.designspace",false,false,new(),[]);var snapshot=w.Capture();Reject(()=>w.Replace(snapshot with{Documents=snapshot.Documents.Add(file)}));Check(w.ActiveDocumentId==id&&ReferenceEquals(before,w.Session.Document));});
        Test("unknown workspace version is rejected",()=>{using var w=Create();Reject(()=>WorkspaceCodec.Write(w.Capture() with{FormatVersion=2}));});
        Test("null workspace collection is rejected",()=>Reject(()=>WorkspaceCodec.Read("{\"formatVersion\":1,\"documents\":null}")));
        Test("missing active document is rejected",()=>{using var w=Create();Reject(()=>WorkspaceCodec.Write(w.Capture() with{ActiveDocumentId=Guid.NewGuid()}));});
        Test("duplicate document identity is rejected",()=>{using var w=Create();var s=w.Capture();Reject(()=>WorkspaceCodec.Write(s with{Documents=[s.Documents[0],s.Documents[0] with{FileName="Other.designspace"}]}));});
        Test("dangling selection is rejected",()=>{using var w=Create();var s=w.Capture();Reject(()=>WorkspaceCodec.Write(s with{Documents=[s.Documents[0] with{Selection=[Guid.NewGuid()]}]}));});
        Test("nonfinite viewport is rejected before replacement",()=>{using var w=Create();Reject(()=>w.UpdateEditor(w.ActiveDocumentId,new(){Zoom=double.NaN}));Check(double.IsFinite(w.Active.Editor.Zoom));});
        Test("invalid view mode is rejected",()=>{using var w=Create();Reject(()=>w.UpdateEditor(w.ActiveDocumentId,new(){Mode="Run arbitrary code"}));});
        Test("workspace document cap prevents unbounded tabs",()=>{using var w=Create();for(var i=1;i<WorkspaceValidator.MaxDocuments;i++)w.Add(DesignDocument.Empty(),"Page"+i+".designspace");Reject(()=>w.Add(DesignDocument.Empty(),"Overflow.designspace"));Check(w.Documents.Count==WorkspaceValidator.MaxDocuments);});
        Test("snapshot geometry uses immutable sharing",()=>{using var w=Create();AddShape(w.Session);var root=w.Session.Document.Root;var snap=w.Capture();Check(ReferenceEquals(root,snap.Documents[0].Document.Root));});
        Test("checkpoint history retains original tree references",()=>{var s=new DesignSession(DesignDocument.Empty());var initial=s.Document;AddShape(s);var checkpoint=s.CaptureCheckpoint();s.Load(DesignDocument.Empty());s.RestoreCheckpoint(checkpoint);s.Undo();Check(ReferenceEquals(initial,s.Document));});
        Test("disposed workspace unsubscribes session events",()=>{var w=Create();var count=0;w.Changed+=(_,_)=>count++;w.Dispose();AddShape(w.Session);Check(count==0);});
        Test("inactive session histories remain bounded",()=>{using var w=Create();w.Session.HistoryLimit=3;var first=w.ActiveDocumentId;for(var i=0;i<10;i++)AddShape(w.Session);w.Add(DesignDocument.Empty(),"Second.designspace");w.Activate(first);Check(w.Session.CaptureCheckpoint().UndoCount==3);});
        Directory.CreateDirectory("artifacts/verification");File.WriteAllText("artifacts/verification/workspace-results.json","{\"passed\":"+passed+",\"failed\":"+failed+"}");
        return(passed,failed);
    }
}
